# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-05 01:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_auto_20190429_0942'),
        ('users', '0002_user_email_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('receiver', models.CharField(max_length=20, verbose_name='收件人')),
                ('place', models.CharField(max_length=100, verbose_name='详细地址')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('tel', models.CharField(max_length=20, null=True, verbose_name='固定电话')),
                ('email', models.CharField(max_length=50, null=True, verbose_name='电子邮箱')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='areas.Areas', verbose_name='市')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='areas.Areas', verbose_name='区县')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='areas.Areas', verbose_name='省')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户地址',
                'db_table': 'tb_addresses',
                'verbose_name_plural': '用户地址',
                'ordering': ['-update_time'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='default_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.Address', verbose_name='用户默认地址'),
        ),
    ]
